### ISSUE TITLE
”卒業制作マッチングアプリプロジェクト”レビュー依頼

### ISSUE THREAD

**Issue by 1222yoshi** [1222yoshi/sotugyou_seisaku#35]
### 実装予定の機能
- [ ] アルバム検索、追加機能
- [ ] アルバム共有機能
- [ ] マッチング機能
- [ ] チャット機能
- [ ] 通知機能
#### MVP後
- [ ] いいね機能
- [ ] 問題出題機能
- [ ] 成績機能

### 必要なページ
- [ ] トップページ（おすすめユーザー一覧）
- [ ] マイページ
- [ ] ＃私を構成する９枚ページ
- [ ] ユーザー詳細ページ
- [ ] チャット一覧ページ
- [ ] チャットルームページ
- [ ] 新規登録ページ
- [ ] ログインページ
- [ ] メールアドレス、パスワード変更ページ
#### MVP後
- [ ] いいねした、されたユーザー一覧ページ
- [ ] テスト一覧、問題、結果ページ

**Comment by Tsuchiya2** [comment]
![image](https://github.com/user-attachments/assets/a7ebef40-0e43-4adc-a957-4ed4c425ef2b)

Projectsにアクセスしましたが、看板・issue・ストーリーポイントが確認できませんでした。上記確認できる状態にして再提出をお願いいたします。

**Comment by 1222yoshi** [comment]
<img width="1408" alt="issue" src="https://github.com/user-attachments/assets/7bea1aff-fec7-4cde-a820-75f5e8ada78e">
すみませんでした。
こちらで未ログイン時でも閲覧できる設定に変更できたと思います。
ご確認のほどよろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
確認できました。
以下コメントになります。

---

・ストーリーポイント4はカリキュラムには無かったかと思います。一度カリキュラムを確認してストーリーポイント3以下になるようにissueを細分化してください。
・ストーリーポイント5のissueもありますが、こちらもカリキュラムに書かれているようにポイント3になるように細分化してください。

**Comment by 1222yoshi** [comment]
ご指摘のとうりストーリーポイントが全て3以下になるように細分化しました。
ご確認のほどよろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

---

以下、MVP後で良いと思ったカードになります。
- メールアドレス変更
- パスワード変更
- チャットルーム
- 通知
