### ISSUE TITLE
8/30MVPレビュー依頼

### ISSUE THREAD

**Issue by 1222yoshi** [1222yoshi/sotugyou_seisaku#54]

**Comment by 1222yoshi** [comment]
## 各種情報
MeTRO NOTE（メトロノート）
https://metronote.jp

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [ ] アルバム検索、追加機能
- [ ] アルバム共有機能
- [ ] マッチング機能

READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください

## READMEレビュー時から変更した機能
マッチングにOpenAIを使用しました。

## サービスイメージがわかるようなスクリーンショット等
特に管理画面など通常ユーザーが触れない機能があったら共有をお願いします
https://gyazo.com/fa6846876669a3f90c3f283b4a376e30
https://gyazo.com/6cd6e8a15b98cecca98a947f2a05c11a
https://gyazo.com/cb8e3eba8cd52df587fdf9df41f18565

レスポンシブ対応のため、レビュー予定日より1日遅れてしまいました。申し訳ございません。
よろしくお願いいたします。

**Comment by tarakish** [comment]
確認しました。以下ご確認をお願いします！
- プロフィール編集にて、画像を選択し保存ボタンを押下すると「名前は必須項目です」とメッセージが表示され保存ができませんでした。
- トップページに自分のアカウントが表示されませんが、こちらは正しい挙動でしょうか？
- マッチング機能については、マッチング度が表示されるのみで「つながる」みたいな機能は存在しない認識であっていますか？
- READMEのMVPリリースに記載されている「チャット機能」が見当たりませんでした。実装されているのであれば利用方法を、実装されていないのであれば「READMEレビュー時から変更した機能」に記載をお願いします。

**Comment by 1222yoshi** [comment]
ご確認、ありがとうございます

プロフィール編集にて失敗した時に名前が入力されてない場合のみを拾って、「名前は必須項目です」

**Comment by tarakish** [comment]
ご対応ありががとうございます。
- プロフィール画像について
  - 改めて対応している形式で試したところ、保存できることが確認できました。
  - `type=field`のinputタグの場合はaccept属性を指定することで指定外の形式のファイルを添付できないようにすることができるので参考にしてみてください。https://developer.mozilla.org/ja/docs/Web/HTML/Attributes/accept

動作確認が取れたのでLGTMです！
引き続き本リリースに向けて開発頑張ってください。
